name: pagify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core app deps
  file_picker: ^10.2.3
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  crypto: ^3.0.3

  # Syncfusion
  syncfusion_flutter_pdfviewer: ^30.1.42
  syncfusion_flutter_pdf: ^30.1.42
  syncfusion_flutter_core: ^30.1.42

  # Firebase (versions compatible with current registry/tooling)
  firebase_core: ^3.8.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.3.0
  firebase_storage: ^12.1.0

  # Sign-in providers
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

msix_config:
  display_name: Pagify
  publisher_display_name: Your Publisher Name
  identity_name: com.yourcompany.pagify
  msix_version: 0.1.0.0
  logo_path: assets/app_icon.png
  start_menu: true
  enable_at_startup: false
  capabilities: internetClient
