// lib/firebase_options.dart
// Generated by hand from your Firebase console values.
// If you re-run `flutterfire configure`, it may overwrite this file.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show kIsWeb, defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        // You don't have a dedicated macOS app; reuse iOS values or add a macOS
        // app in the Firebase console and update this.
        return ios;
      case TargetPlatform.windows:
        return windows; // registered as a Web app in your project
      case TargetPlatform.linux:
        // No Linux app set up; reuse Windows/web-style config.
        return windows;
      case TargetPlatform.fuchsia:
        // Not supported; reuse Windows/web-style config.
        return windows;
    }
  }

  // ---------------- Web (also used by Windows app created as "web") ----------------
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4m-J6ZyDSbnk8G62jcGQGJACwTk00_d0',
    appId: '1:1053452200065:web:f87b07c8b8f263ac900580',
    messagingSenderId: '1053452200065',
    projectId: 'pagify-aa8da',
    storageBucket: 'pagify-aa8da.firebasestorage.app',
    authDomain: 'pagify-aa8da.firebaseapp.com', // <-- required for web auth
    measurementId: 'G-8QDJQ6TRKW',
  );

  // ---------------- Android ----------------
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ictaVLDM1f0e1Q4U2a_2FWzpU-ZSueE',
    appId: '1:1053452200065:android:48597c889b66adf4900580',
    messagingSenderId: '1053452200065',
    projectId: 'pagify-aa8da',
    storageBucket: 'pagify-aa8da.firebasestorage.app',
  );

  // ---------------- iOS (and macOS fallback) ----------------
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpk-vS_Qt--12nldabovwPan9RRM9apns',
    appId: '1:1053452200065:ios:3c2805e82fd987cb900580',
    messagingSenderId: '1053452200065',
    projectId: 'pagify-aa8da',
    storageBucket: 'pagify-aa8da.firebasestorage.app',
    iosBundleId: 'com.example.pagify',
  );

  // ---------------- Windows (your Firebase project created a “web” app for it) ----
  // Using the same values as Web works for desktop in Flutter.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4m-J6ZyDSbnk8G62jcGQGJACwTk00_d0',
    appId: '1:1053452200065:web:f87b07c8b8f263ac900580',
    messagingSenderId: '1053452200065',
    projectId: 'pagify-aa8da',
    storageBucket: 'pagify-aa8da.firebasestorage.app',
    authDomain: 'pagify-aa8da.firebaseapp.com',
    measurementId: 'G-8QDJQ6TRKW',
  );
}
